spring.application.name=meconecta
spring.datasource.url=jdbc:postgresql://localhost:5433/meconecta
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update